### ISSUE TITLE
req.body.name or req.body.password is undefined when using POST to register

### ISSUE THREAD

**Issue by isaacmichaan** [emaitee/jwt-passport-mysql#1]

**Comment by emaitee** [comment]
Sorry, I'm sure this is coming rather late, are you still facing this challenge?

**Comment by isaacmichaan** [comment]
Don't remember, but thanks :)

________________________________
De: Mustapha Issa Toyin <notifications@github.com>
Enviado: segunda-feira, 23 de março de 2020 14:40
Para: emaitee/jwt-passport-mysql <jwt-passport-mysql@noreply.github.com>
Cc: Isaac Michaan <isaacmichaan@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [emaitee/jwt-passport-mysql] req.body.name or req.body.password is undefined when using POST to register (#1)


Sorry, I'm sure this is coming rather late, are you still facing this challenge?

**Comment by emaitee** [comment]
Okay, I'm closing this
